### PR TITLE
recreated CI config for maven tycho travis from script

### PR DESCRIPTION
**Pull request by max-kramer**

### CODE REVIEW

**Comment by jGleitz** [comment]
@max-kramer The build was failing!

**Comment by HeikoKlare** [comment]
I would recommend activating requried status checks for the master branch to avoid merging builds that fail.
For sure, admins can still merge, but at least they get an emphatic warning.

**Comment by max-kramer** [comment]
Even without the warning I new that the build temporarily failed due to connectivity problems of the eclipse repo. Now the build succeeded (without any further changes). Nevertheless, I activated the required CI check for the master branch.

**Comment by HeikoKlare** [comment]
Ah okay, but nevertheless we should only merge when the build succeeds to ensure that the build is deployed. Otherweise, someone has to remember to rerun the build to have the current version deployed.

**Pull request merged**
